


DROP TABLE  if exists `ENTRY`;
DROP TABLE  if exists `DALIY_REPORT`;
DROP TABLE  if exists `STUDENT`;
DROP TABLE  if exists `LESSON`;
DROP TABLE  if exists `TRAINING_TYPE`;


CREATE TABLE `STUDENT` (

`ID` int(10) NOT NULL AUTO_INCREMENT,

`SCHOOL_ID` char(10) NOT NULL,

`NAME` varchar(200) NOT NULL,

`SEX` char(2) NOT NULL,

`AGE` int(3) NULL,

`TYPE` varchar(200) NOT NULL,

`SCHOOL` varchar(300) NULL,

`TUTOR` varchar(200) NOT NULL,

`CREATE_AT` long NOT NULL,

`CREATOR` varchar(200) NOT NULL,

`UPDATE_AT` long NOT NULL,

`UPDATER` varchar(200) NOT NULL DEFAULT '',

`VERSION` int(3) NOT NULL DEFAULT 0,

PRIMARY KEY (`ID`, `SCHOOL_ID`)

) DEFAULT CHARSET=utf8;



UPDATE ENTRY SET PROMISE= '老大最帅'　where SCHOOL_ID = 'JS_4567';

CREATE TABLE `ENTRY` (

`ENTRY_ID` int(10) NOT NULL AUTO_INCREMENT,

`LESSON_ID` int(10) NOT NULL,

`SCHOOL_ID` char(10) NOT NULL,

`QQ_ID` varchar(20) NOT NULL,

`HOPE_ENTRY_DATE` long NOT NULL,

`DAILY_REPORT` varchar(800) NOT NULL,

`PROMISE` varchar(300) NOT NULL,

`SOURCE` varchar(300) NULL,

`STATUS` char(2) NULL,

`CREATE_AT` long NOT NULL,

`CREATOR` varchar(200) NOT NULL,

`UPDATE_AT` long NOT NULL,

`UPDATER` varchar(200) NOT NULL,

`VERSION` int(3) NOT NULL DEFAULT 0,

PRIMARY KEY (`ENTRY_ID`, `LESSON_ID`, `SCHOOL_ID`)

) DEFAULT CHARSET=utf8;



insert into LESSON (LESSON_NAME,LESSON_TYPE,START_DATE,SEMESTER,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('线下学员招募', '线下', 20180102, 5, curdate(), '大饼', 0, '', VERSION + 1)
insert into ENTRY (LESSON_ID,SCHOOL_ID,QQ_ID,HOPE_ENTRY_DATE, PROMISE,
DAILY_REPORT, SOURCE, CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values (1, 'JS_4567', '1161999360', 20171101,
'11',
'',
'', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊1', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊2', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊3', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊4', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊5', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊6', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊7', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊8', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);
insert into STUDENT (SCHOOL_ID,NAME,SEX,AGE,TYPE,SCHOOL,TUTOR,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('JS_4567', '姚磊9', '男', 25, '前端工程师', '南京工业大学浦江学院', '孙伟淳', curdate(), '大饼', 0, '', VERSION + 1);

insert into ENTRY (LESSON_ID,SCHOOL_ID,QQ_ID,HOPE_ENTRY_DATE, DAILY_REPORT, PROMISE, CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values (1, 'JS_4567', '1161999360', 20171101, 'aaa', 'bbb', curdate(), 'aa', 0, '', VERSION + 1);


CREATE TABLE `LESSON` (

`LESSON_ID` int(10) NOT NULL AUTO_INCREMENT,

`LESSON_NAME` varchar(300) NOT NULL,

`LESSON_TYPE` varchar(100) NULL,

`START_DATE` long NULL,

`SEMESTER` int(5) NULL,

`CREATE_AT` long NOT NULL,

`CREATOR` varchar(200) NOT NULL,

`UPDATE_AT` long NOT NULL,

`UPDATER` varchar(200) NOT NULL,

`VERSION` int(3) NOT NULL DEFAULT 0,

PRIMARY KEY (`LESSON_ID`)

) DEFAULT CHARSET=utf8;



insert into TRAINING_TYPE (SCHOOL_ID,TITLE,BODY,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('前端工程师',  curdate(), '大饼', 0, '', VERSION + 1)

CREATE TABLE `DALIY_REPORT` (

`REPORT_ID` int(10) NOT NULL AUTO_INCREMENT,

`SCHOOL_ID` char(10) NOT NULL,

`TITLE` varchar(255) NOT NULL,

`BODY` varchar(255) NOT NULL,

`CREATE_AT` long NOT NULL,

`CREATOR` varchar(200) NOT NULL,

`UPDATE_AT` long NOT NULL,

`UPDATER` varchar(200) NOT NULL,

`VERSION` int(3) NOT NULL DEFAULT 0,

PRIMARY KEY (`REPORT_ID`)

) DEFAULT CHARSET=utf8;


insert into TRAINING_TYPE (TYPE_NAME,CREATE_AT,CREATOR,UPDATE_AT,UPDATER,VERSION)
values ('前端工程师',  curdate(), '大饼', 0, '', VERSION + 1)


CREATE TABLE `TRAINING_TYPE` (

`TRANING_TYPE_ID` int(10) NOT NULL,

`TYPE_NAME` varchar(200) NOT NULL,

`CREATE_AT` long NOT NULL,

`CREATOR` varchar(200) NOT NULL,

`UPDATE_AT` long NOT NULL,

`UPDATER` varchar(200) NOT NULL,

`VERSION` int(3) NOT NULL DEFAULT 0,

PRIMARY KEY (`TRANING_TYPE_ID`)

) DEFAULT CHARSET=utf8;


ALTER TABLE `ENTRY` ADD CONSTRAINT `SCHOOL_ID` FOREIGN KEY (`SCHOOL_ID`) REFERENCES `STUDENT` (`SCHOOL_ID`);

ALTER TABLE `DALIY_REPORT` ADD CONSTRAINT `SCHOOL_ID_2` FOREIGN KEY (`SCHOOL_ID`) REFERENCES `STUDENT` (`SCHOOL_ID`);

ALTER TABLE `ENTRY` ADD CONSTRAINT `LESSON_ID` FOREIGN KEY (`LESSON_ID`) REFERENCES `LESSON` (`LESSON_ID`);

ALTER TABLE `STUDENT` ADD CONSTRAINT `TYPE` FOREIGN KEY (`TYPE`) REFERENCES `TRAINING_TYPE` (`TYPE_NAME`);
